// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkPKfZAjhuQnoMB34xZgL2-saHAnCvIWg',
    appId: '1:695826443755:web:3073f23c4fea70b478bdae',
    messagingSenderId: '695826443755',
    projectId: 'medilife-26ef9',
    authDomain: 'medilife-26ef9.firebaseapp.com',
    storageBucket: 'medilife-26ef9.firebasestorage.app',
    measurementId: 'G-7WD58978ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3l2NeCdN0qYMFgvdjzWdhrUaX2S9QAHI',
    appId: '1:695826443755:android:1b8f64e6578f07b078bdae',
    messagingSenderId: '695826443755',
    projectId: 'medilife-26ef9',
    storageBucket: 'medilife-26ef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGLvmykd7tgAHtYdxLJPIDxptJnjg9dME',
    appId: '1:695826443755:ios:938f28d9064ced1578bdae',
    messagingSenderId: '695826443755',
    projectId: 'medilife-26ef9',
    storageBucket: 'medilife-26ef9.firebasestorage.app',
    iosBundleId: 'com.example.mediLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGLvmykd7tgAHtYdxLJPIDxptJnjg9dME',
    appId: '1:695826443755:ios:938f28d9064ced1578bdae',
    messagingSenderId: '695826443755',
    projectId: 'medilife-26ef9',
    storageBucket: 'medilife-26ef9.firebasestorage.app',
    iosBundleId: 'com.example.mediLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkPKfZAjhuQnoMB34xZgL2-saHAnCvIWg',
    appId: '1:695826443755:web:326e841ffe9c737178bdae',
    messagingSenderId: '695826443755',
    projectId: 'medilife-26ef9',
    authDomain: 'medilife-26ef9.firebaseapp.com',
    storageBucket: 'medilife-26ef9.firebasestorage.app',
    measurementId: 'G-FV4KX1R46E',
  );
}
